тз 19
KseniaYakovenko/plus-smart-home-tech pull request #1
Opened 2024-10-14 20:42 UTC by KseniaYakovenko

2024-10-15 11:18 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара замечаний, которые необходимо исправить!

Желаю удачи!

2024-10-15 11:18 UTC, LexLippi commented on telemetry/collector/src/main/java/ru/yandex/practicum/service/handler/ScenarioAddedEventHandler.java
> +        return ScenarioAddedEventAvro.newBuilder()
Когда используем шаблон-строитель в продакшен-коде, всегда стоит задаваться вопросом, а что будет, если в наш объект добавятся новые поля?

В таком случае мы можем забыть их прокинуть во все строители и наше приложение будеть крашиться из-за непредвиденных `NullPointerException`, которые мы могли поймать во время компиляции, если бы использовали конструктор, а не строитель, а не в рантайме.

Поэтому с использрванием шаблона строитель нужно всегда быть осторожным :)

2024-10-15 11:18 UTC, LexLippi commented on telemetry/collector/src/main/java/ru/yandex/practicum/service/handler/ScenarioAddedEventHandler.java
> +        ScenarioAddedEvent scenarioEvent = (ScenarioAddedEvent) event;
можно ограничиться следующим кастингом:

```java
var scenatioEvent = (ScenarioAddedEvent) event;
```

Чтобы дважды не писать `ScenarioAddedEvent`

2024-10-15 11:18 UTC, LexLippi commented on telemetry/collector/src/main/java/ru/yandex/practicum/model/ScenarioRemovedEvent.java
> +//    minLength: 3
Это здесь зачем?)

2024-10-15 11:18 UTC, LexLippi commented on telemetry/collector/src/main/java/ru/yandex/practicum/model/ScenarioCondition.java
> +@ToString
Может `@Data` использовать?

2024-10-15 11:18 UTC, LexLippi commented on telemetry/collector/src/main/java/ru/yandex/practicum/model/HubEvent.java
> +    // @NotBlank
Убрать если не нужно

2024-10-15 11:18 UTC, LexLippi commented on telemetry/collector/src/main/java/ru/yandex/practicum/model/DeviceAddedEvent.java
> +    // @NotBlank
Убрать если не нужно

2024-10-15 11:18 UTC, LexLippi commented on telemetry/collector/src/main/java/ru/yandex/practicum/model/DeviceAction.java
> +@ToString
Может `@Data`?

2024-10-15 11:47 UTC, KseniaYakovenko commented on telemetry/collector/src/main/java/ru/yandex/practicum/model/DeviceAddedEvent.java
> +    // @NotBlank
убрала

2024-10-15 11:48 UTC, KseniaYakovenko commented on telemetry/collector/src/main/java/ru/yandex/practicum/model/HubEvent.java
> +    // @NotBlank
убрала

2024-10-15 11:50 UTC, KseniaYakovenko commented on telemetry/collector/src/main/java/ru/yandex/practicum/model/ScenarioCondition.java
> +@ToString
спасибо, заменила

2024-10-15 11:50 UTC, KseniaYakovenko commented on telemetry/collector/src/main/java/ru/yandex/practicum/model/ScenarioRemovedEvent.java
> +//    minLength: 3
убрала

2024-10-15 11:54 UTC, KseniaYakovenko commented on telemetry/collector/src/main/java/ru/yandex/practicum/service/handler/ScenarioAddedEventHandler.java
> +        ScenarioAddedEvent scenarioEvent = (ScenarioAddedEvent) event;
спасибо, заменила везде

2024-10-15 12:19 UTC, KseniaYakovenko commented on telemetry/collector/src/main/java/ru/yandex/practicum/service/handler/ScenarioAddedEventHandler.java
> +        return ScenarioAddedEventAvro.newBuilder()
спасибо, заменила везде на конструктор

2024-10-15 12:40 UTC, KseniaYakovenko commented on telemetry/collector/src/main/java/ru/yandex/practicum/model/DeviceAction.java
> +@ToString
заменила

2024-10-16 13:42 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих проектах!

2024-10-20 20:15 UTC, merged