7 spring cloud microservices
KseniaYakovenko/plus-smart-home-tech pull request #11
Opened 2024-11-23 22:20 UTC by KseniaYakovenko

2024-11-25 10:03 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-11-25 10:03 UTC, LexLippi commented on commerce/warehouse/src/main/resources/schema.sql
> +    shopping_cart_id UUID             NOT NULL,
Думаю на это поле не помешал бы внешний ключ или индекс

2024-11-25 10:03 UTC, LexLippi commented on commerce/warehouse/src/main/resources/schema.sql
> +    product_id UUID    NOT NULL,
Думаю на это поле не помешал бы внешний ключ или индекс

2024-11-25 10:03 UTC, LexLippi commented on commerce/warehouse/src/main/java/ru/yandex/practicum/service/WarehouseServiceImpl.java
> +        } else if (quantity > 0 && quantity < LIMIT_COUNT) {
`else` не нужен, если делаем `return` в условном операторе

2024-11-25 10:03 UTC, LexLippi commented on commerce/warehouse/src/main/java/ru/yandex/practicum/service/WarehouseServiceImpl.java
> +        return new AddressDto("Country", "City", "Street", "1", "2");
Лучше константы сохранять в переменные класса и давать им понятные имена, или писать пояснения, почему используется то или иное заполнение объекта, если оно не очевидное

2024-11-25 12:03 UTC, KseniaYakovenko commented on commerce/warehouse/src/main/java/ru/yandex/practicum/service/WarehouseServiceImpl.java
> +        return new AddressDto("Country", "City", "Street", "1", "2");
исправила

2024-11-25 12:05 UTC, KseniaYakovenko commented on commerce/warehouse/src/main/java/ru/yandex/practicum/service/WarehouseServiceImpl.java
> +        } else if (quantity > 0 && quantity < LIMIT_COUNT) {
спасибо, исправила

2024-11-25 12:10 UTC, KseniaYakovenko commented on commerce/warehouse/src/main/resources/schema.sql
> +    product_id UUID    NOT NULL,
спасибо, добавила

2024-11-25 12:52 UTC, KseniaYakovenko commented on commerce/warehouse/src/main/resources/schema.sql
> +    shopping_cart_id UUID             NOT NULL,
добавила индекс

2024-11-26 14:36 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи!

2024-11-26 16:39 UTC, merged