Техническое задание проекта спринта №22-gateway-microservices
KseniaYakovenko/plus-smart-home-tech pull request #13
Opened 2024-12-08 00:02 UTC by KseniaYakovenko

2024-12-09 09:06 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-12-09 09:06 UTC, LexLippi commented on commerce/payment/src/main/java/ru/yandex/practicum/service/PaymentServiceImpl.java
> +    }
Эти методы тоже лучше пометить, как `@Transactional`, но с параметром `readonly`. 

https://blog.vvauban.com/blog/using-transactional-readonly-true-in-spring-applications-is-highly

2024-12-09 09:06 UTC, LexLippi commented on commerce/payment/src/main/java/ru/yandex/practicum/controller/PaymentController.java
> +    @PostMapping("/totalCost")
Но это же `get`-метод, почему ты используешь `PostMapping`?

2024-12-09 09:06 UTC, LexLippi commented on commerce/payment/src/main/java/ru/yandex/practicum/controller/PaymentController.java
> +    @PostMapping("/productCost")
Аналогично про `get`-метод и `PostMapping`

2024-12-09 09:06 UTC, LexLippi commented on commerce/order/src/main/java/ru/yandex/practicum/service/OrderServiceImpl.java
> +    public List<OrderDto> getClientOrders(String username) {
Не помешает `Transactional(readOnly=true)`

2024-12-09 09:06 UTC, LexLippi commented on commerce/delivery/src/main/resources/schema.sql
> +);
Немного странно, что у нас две полностью идентичных таблицы адресов, может нам достаточно будет одной? Или в этом есть какой-то скрытый смысл?

2024-12-09 09:06 UTC, LexLippi commented on commerce/delivery/src/main/java/ru/yandex/practicum/service/DeliveryServiceImpl.java
> +public class DeliveryServiceImpl implements DeliveryService {
Про `readonly`-транзакции уже писал

2024-12-09 09:20 UTC, KseniaYakovenko commented on commerce/payment/src/main/java/ru/yandex/practicum/controller/PaymentController.java
> +    @PostMapping("/totalCost")
В спецификации задания это POST метод для расчёта полной стоимости заказа.

2024-12-09 09:22 UTC, KseniaYakovenko commented on commerce/payment/src/main/java/ru/yandex/practicum/controller/PaymentController.java
> +    @PostMapping("/productCost")
в спецификации задания это тоже POST.

2024-12-09 10:46 UTC, KseniaYakovenko commented on commerce/payment/src/main/java/ru/yandex/practicum/service/PaymentServiceImpl.java
> +    }
спасибо, добавила

2024-12-09 10:48 UTC, KseniaYakovenko commented on commerce/order/src/main/java/ru/yandex/practicum/service/OrderServiceImpl.java
> +    public List<OrderDto> getClientOrders(String username) {
добавила

2024-12-09 10:50 UTC, KseniaYakovenko commented on commerce/delivery/src/main/java/ru/yandex/practicum/service/DeliveryServiceImpl.java
> +public class DeliveryServiceImpl implements DeliveryService {
исправила

2024-12-09 10:54 UTC, KseniaYakovenko commented on commerce/delivery/src/main/resources/schema.sql
> +);
смысл в полном разделении микросервисов по источникам данных, один сервис - одна бд/схема, для упрощения в задании делала в одной бд

2024-12-10 08:16 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-12-10 10:36 UTC, merged