Техническое задание 20. Analyzer
KseniaYakovenko/plus-smart-home-tech pull request #5
Opened 2024-11-02 11:59 UTC by KseniaYakovenko

2024-11-03 12:54 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которое необходимо исправить!

Желаю удачи!

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/resources/schema.sql
> +    IF (SELECT hub_id FROM scenarios WHERE id = NEW.scenario_id) != (SELECT hub_id FROM sensors WHERE id = NEW.sensor_id) THEN
Лучше использовать оператор `<>` из стандарта `SQL` для проверки на несовпадение:

https://www.postgresql.org/docs/current/functions-comparison.html

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/resources/schema.sql
> +                                         name VARCHAR NOT NULL,
У полей типа `varchar` всегда стоит указывать ограничение на размер так как это влияет на эффективность запросов:

https://stackoverflow.com/questions/4324872/does-varchar-size-limit-matter

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/resources/schema.sql
> +    PRIMARY KEY (scenario_id, sensor_id, condition_id)
Я советую использовать более простые первичные ключи, а эти поля ограничивать с помощью ключевого слова `unique`. [Здесь ](https://stackoverflow.com/questions/69226319/why-composite-primary-key-when-i-can-use-single-primary-key-with-unique-constrai) приведены разумные аргументы, почему это хороший вариант. Но если тебе это сильно не нравится, то можешь оставить так)

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/resources/schema.sql
> +                                       id VARCHAR PRIMARY KEY,
Если мы вдруг захотим поменять тип данных у этого поля, или изменить размер, придется менять много других таблиц, так как это первичный ключ, возможно, проще использовать порядковый идентификатор в качестве первичного ключа

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/service/SensorService.java
> +        if (!existsBySensorIdsAndHubId(hubId, sensorId)) {
Обычно для уменьшения вложенности, пишут:

```java
if (existsBySensorIdsAndHubId(hubId, sensorId)) {
    return;
}
Sensor sensor = new Sensor();
sensor.setId(sensorId);
sensor.setHubId(hubId);
sensorRepository.save(sensor);
```

Но это вкусовщина :)

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/service/ScenarioService.java
> +        } else if (value instanceof Boolean) {
`else` не нужен

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/service/ScenarioService.java
> +        } else {
`else` не нужен

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/service/HubEventProcessor.java
> +    }
Такие комментарии лучше сразу удалять иначе они впоследствии сильно засоряют код

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/kafka/AnalyzerKafkaConfig.java
> +    @ToString
Вместо этого можно использовать одну аннотацию `@Data`

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/kafka/AnalyzerKafkaConfig.java
> +        public ConsumerConfig consumer;
Это нарушает инкапсуляцию данного объекта, лучше не делать эти поля публичными

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/kafka/AnalyzerKafkaConfig.java
> +//        }
Такие комментарии лучше не хранить

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/entity/Sensor.java
> +@ToString
Можно `@Data`

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/entity/Scenario.java
> +@ToString
Можно `@Data`

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/entity/Condition.java
> +@ToString
Можно `@Data`

2024-11-03 12:54 UTC, LexLippi commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/entity/Action.java
> +@ToString
Можно `@Data`

2024-11-03 12:54 UTC, LexLippi commented on telemetry/aggregator/src/main/java/ru/yandex/practicum/kafka/configuration/KafkaConfig.java
> +//        }
Такие комментарии лучше удалять

2024-11-03 12:54 UTC, LexLippi commented on telemetry/aggregator/src/main/java/ru/yandex/practicum/kafka/configuration/KafkaConfig.java
> +@ToString
Можно `@Data`

2024-11-03 14:22 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/resources/schema.sql
> +    IF (SELECT hub_id FROM scenarios WHERE id = NEW.scenario_id) != (SELECT hub_id FROM sensors WHERE id = NEW.sensor_id) THEN
спасибо, исправила

2024-11-03 14:30 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/resources/schema.sql
> +                                         name VARCHAR NOT NULL,
спасибо, указала

2024-11-03 14:41 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/resources/schema.sql
> +    PRIMARY KEY (scenario_id, sensor_id, condition_id)
спасибо, исправила

2024-11-03 14:44 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/service/SensorService.java
> +        if (!existsBySensorIdsAndHubId(hubId, sensorId)) {
поправила

2024-11-03 14:45 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/entity/Scenario.java
> +@ToString
поправила

2024-11-03 14:50 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/entity/Condition.java
> +@ToString
поправила

2024-11-03 14:50 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/entity/Action.java
> +@ToString
поправила

2024-11-03 14:52 UTC, KseniaYakovenko commented on telemetry/aggregator/src/main/java/ru/yandex/practicum/kafka/configuration/KafkaConfig.java
> +//        }
удалила

2024-11-03 14:53 UTC, KseniaYakovenko commented on telemetry/aggregator/src/main/java/ru/yandex/practicum/kafka/configuration/KafkaConfig.java
> +@ToString
поправила

2024-11-03 15:02 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/service/ScenarioService.java
> +        } else if (value instanceof Boolean) {
исправила

2024-11-03 15:02 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/service/ScenarioService.java
> +        } else {
исправила

2024-11-03 15:03 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/service/HubEventProcessor.java
> +    }
удалила

2024-11-03 15:04 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/kafka/AnalyzerKafkaConfig.java
> +//        }
удалила

2024-11-03 15:16 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/kafka/AnalyzerKafkaConfig.java
> +    @ToString
заменила

2024-11-03 15:16 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/kafka/AnalyzerKafkaConfig.java
> +        public ConsumerConfig consumer;
исправила

2024-11-03 15:16 UTC, KseniaYakovenko commented on telemetry/analyzer/src/main/java /ru.yandex.practicum/entity/Sensor.java
> +@ToString
заменила

2024-11-04 20:45 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи!

2024-11-05 14:25 UTC, merged